-- MySQL Script generated by MySQL Workbench
-- Mon Oct 21 10:45:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pesquisa_preferencias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pesquisa_preferencias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pesquisa_preferencias` DEFAULT CHARACTER SET utf8 ;
USE `pesquisa_preferencias` ;

-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_clima` (
  `cod_clima` INT NOT NULL AUTO_INCREMENT,
  `clima` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_clima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_animal_estimacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_animal_estimacao` (
  `cod_animal_estimacao` INT NOT NULL AUTO_INCREMENT,
  `animal_estimacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_animal_estimacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_bebida` (
  `cod_bebida` INT NOT NULL AUTO_INCREMENT,
  `bebida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_hobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_hobby` (
  `cod_hobby` INT NOT NULL AUTO_INCREMENT,
  `hobby` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_hobby`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_atividade_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_atividade_fisica` (
  `cod_atividade_fisica` INT NOT NULL AUTO_INCREMENT,
  `atividade_fisica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_atividade_fisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_preferencia_musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_preferencia_musical` (
  `cod_preferencia_musical` INT NOT NULL AUTO_INCREMENT,
  `preferencia_musical` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_preferencia_musical`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_educacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_educacao` (
  `cod_educacao` INT NOT NULL AUTO_INCREMENT,
  `educacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_educacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_estado_civil` (
  `cod_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_estado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_estado` (
  `cod_estado` INT NOT NULL AUTO_INCREMENT,
  `sigla_estado` CHAR(2) NOT NULL,
  `regiao` VARCHAR(45) NOT NULL,
  `renda_mensal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_pessoa` (
  `cod_pessoa` INT NOT NULL,
  `cod_estado_civil` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  `cod_educacao` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `idade` INT NOT NULL,
  `peso` DECIMAL(10,2) NOT NULL,
  `colesterol` DECIMAL(10,2) NOT NULL,
  `renda_mensal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_pessoa`),
  INDEX `fk_tb_pessoa_tb_educacao1_idx` (`cod_educacao` ASC) VISIBLE,
  INDEX `fk_tb_pessoa_tb_estado_civil1_idx` (`cod_estado_civil` ASC) VISIBLE,
  INDEX `fk_tb_pessoa_tb_estado1_idx` (`cod_estado` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pessoa_tb_educacao1`
    FOREIGN KEY (`cod_educacao`)
    REFERENCES `pesquisa_preferencias`.`tb_educacao` (`cod_educacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pessoa_tb_estado_civil1`
    FOREIGN KEY (`cod_estado_civil`)
    REFERENCES `pesquisa_preferencias`.`tb_estado_civil` (`cod_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pessoa_tb_estado1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `pesquisa_preferencias`.`tb_estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa_preferencias`.`tb_pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa_preferencias`.`tb_pesquisa` (
  `cod_pesquisa` INT NOT NULL AUTO_INCREMENT,
  `data_pesquisa` DATE NOT NULL,
  `cod_pessoa` INT NOT NULL,
  `cod_animal_estimacao` INT NOT NULL,
  `cod_bebida` INT NOT NULL,
  `cod_atividade_fisica` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  `cod_hobby` INT NOT NULL,
  `cod_preferencia_musical` INT NOT NULL,
  PRIMARY KEY (`cod_pesquisa`),
  INDEX `fk_tb_pesquisa_tb_animal_estimacao_idx` (`cod_animal_estimacao` ASC) VISIBLE,
  INDEX `fk_tb_pesquisa_tb_bebida1_idx` (`cod_bebida` ASC) VISIBLE,
  INDEX `fk_tb_pesquisa_tb_atividade_fisica1_idx` (`cod_atividade_fisica` ASC) VISIBLE,
  INDEX `fk_tb_pesquisa_tb_clima1_idx` (`cod_clima` ASC) VISIBLE,
  INDEX `fk_tb_pesquisa_tb_hobby1_idx` (`cod_hobby` ASC) VISIBLE,
  INDEX `fk_tb_pesquisa_tb_pessoa1_idx` (`cod_pessoa` ASC) VISIBLE,
  INDEX `fk_tb_pesquisa_tb_preferencia_musical1_idx` (`cod_preferencia_musical` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pesquisa_tb_animal_estimacao`
    FOREIGN KEY (`cod_animal_estimacao`)
    REFERENCES `pesquisa_preferencias`.`tb_animal_estimacao` (`cod_animal_estimacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesquisa_tb_bebida1`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `pesquisa_preferencias`.`tb_bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesquisa_tb_atividade_fisica1`
    FOREIGN KEY (`cod_atividade_fisica`)
    REFERENCES `pesquisa_preferencias`.`tb_atividade_fisica` (`cod_atividade_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesquisa_tb_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `pesquisa_preferencias`.`tb_clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesquisa_tb_hobby1`
    FOREIGN KEY (`cod_hobby`)
    REFERENCES `pesquisa_preferencias`.`tb_hobby` (`cod_hobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesquisa_tb_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `pesquisa_preferencias`.`tb_pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pesquisa_tb_preferencia_musical1`
    FOREIGN KEY (`cod_preferencia_musical`)
    REFERENCES `pesquisa_preferencias`.`tb_preferencia_musical` (`cod_preferencia_musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
